### ISSUE TITLE
Correct the gnss node syntax

### ISSUE THREAD

**Issue by clementlgl** [catie-aq/zephyr_zest-radio-gnss#11]
https://github.com/catie-aq/zephyr_zest-radio-gnss/blob/3e583e39e8c7dc58888fdfa9ba8a44ba623bc7be/boards/shields/zest-radio-gnss/zest_radio_gnss.overlay#L16

I think the node name should be `l86` or `lc86g` instead of `gnss`.

**Comment by j-delsol-dev** [comment]
https://github.com/catie-aq/zephyr_zest-radio-gnss/blob/3e583e39e8c7dc58888fdfa9ba8a44ba623bc7be/boards/shields/zest-radio-gnss/zest_radio_gnss.overlay#L17

Use the quectel `l86` modem instead of `lc86g`.
